### ISSUE TITLE
Bezirk Trips

### ISSUE THREAD

**Issue by Fabsi110** [citmp2015/taxi#1]
Welcher Bezirk frequentiert am häufigsten?
bzw. von nach...

**Comment by MonsJovis** [comment]
[district_tips_boroughs.txt](https://github.com/citmp2015/taxi/files/31919/district_tips_boroughs.txt)
[district_tips_neighborhood.txt](https://github.com/citmp2015/taxi/files/31918/district_tips_neighborhood.txt)
