### ISSUE TITLE
GEO-Daten von Bezirken raussuchen +  Mapping

### ISSUE THREAD

**Issue by Fabsi110** [citmp2015/taxi#8]

**Comment by GerritJa** [comment]
Hi, habe die pickup/dropoff-Koordinaten nun auf die districts mappen können. Dabei konnte ich leider beim mapping nicht die Funktionen der Geotools nutzen, da für die Broadcastvariablen anscheinend nur POJO-Typen genutzt werden können (https://ci.apache.org/projects/flink/flink-docs-release-0.8/programming_guide.html), die keine komplexen Datentypen oder Vererbungen zulassen.  Für die Zuordnung der Koordinaten zu den Districts habe ich daher diesen Code genutzt: http://stackoverflow.com/questions/12083093/how-to-define-if-a-determinate-point-is-inside-a-region-lat-long. Er scheint korrekt zu sein, lediglich bei Datensätzen mit long=lat=0.000 kommt kein District raus. Das sind scheinbar Taxis ohne GPS. Für das Einlesen der .csv kann die env.readCsvFile(..) genutzt werden ... wenns eine POJO-Klasse ist. Ich habe mal die Taxidrive Klasse leicht angepasst (keine Datetime-Objekte), dann funktionierts - Ich hoffe damit sind alle einverstanden.
