### ISSUE TITLE
Heatmap JS Library Analyse + Prototyp

### ISSUE THREAD

**Issue by Fabsi110** [citmp2015/taxi#9]

**Comment by MonsJovis** [comment]
see b6def05d0efd919b30de214c2e1a415c560f03ad

**Comment by MonsJovis** [comment]
The heatmap makes no sense for group data. So we decided to visualize the data filling NYCs boroughs  with different gradients. 

The easiest way to do this, is Google Fusion Tables:
https://www.google.com/fusiontables/DataSource?docid=1Y4xrfRIo4wghNc2MG9wjs1h8G6VKh3jHvW4Rfxbb
